# Generated by Django 4.2.7 on 2023-11-02 18:41

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default=1, upload_to='Arts/images', validators=[market.models.validate_file_size]),
            preserve_default=False,
        ),
    ]
