# Generated by Django 4.2.7 on 2023-11-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_remove_artwork_image_url_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Arts/images', validators=[market.validators.validate_file_size]),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('A', 'Artist'), ('U', 'User')], default='U', max_length=1)),
                ('list_arts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_arts', to='market.artwork')),
                ('list_buy_arts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_buy_arts', to='market.artwork')),
                ('list_sell_arts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_sell_arts', to='market.artwork')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
