# Generated by Django 4.2.7 on 2023-11-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_artwork_image_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='list_arts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_arts', to='market.artwork'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='list_buy_arts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_buy_arts', to='market.artwork'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='list_sell_arts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_sell_arts', to='market.artwork'),
        ),
    ]
