# Generated by Django 4.2.7 on 2023-11-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_customer_options_remove_customer_list_arts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.customer'),
        ),
        migrations.RemoveField(
            model_name='listart',
            name='list_arts',
        ),
        migrations.RemoveField(
            model_name='listart',
            name='list_buy_arts',
        ),
        migrations.RemoveField(
            model_name='listart',
            name='list_sell_arts',
        ),
        migrations.AddField(
            model_name='listart',
            name='list_arts',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_arts', to='market.artwork'),
        ),
        migrations.AddField(
            model_name='listart',
            name='list_buy_arts',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_buy_arts', to='market.artwork'),
        ),
        migrations.AddField(
            model_name='listart',
            name='list_sell_arts',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_sell_arts', to='market.artwork'),
        ),
    ]
