# Generated by Django 4.2.7 on 2023-11-03 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_alter_listart_customer_remove_listart_list_arts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listart',
            name='list_arts',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listart',
            name='list_buy_arts',
            field=models.ManyToManyField(blank=True, related_name='list_buy_arts', to='market.artwork'),
        ),
        migrations.AlterField(
            model_name='listart',
            name='list_sell_arts',
            field=models.ManyToManyField(blank=True, related_name='list_sell_arts', to='market.artwork'),
        ),
    ]
