# Generated by Django 4.2.7 on 2023-11-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_artwork_artist_alter_artwork_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listart',
            name='list_arts',
            field=models.ManyToManyField(blank=True, related_name='list_arts', to='market.artwork'),
        ),
    ]
