# Generated by Django 4.2.7 on 2023-11-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_rename_unit_price_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
