# Generated by Django 4.2.7 on 2023-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_artwork_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
